### ISSUE TITLE
Cannot find module TDocDeployer

### ISSUE THREAD

**Issue by hughht5** [Open-Attestation/token-registry#125]
When i run 'npx hardhat test' or 'npx hardhat deploy:token --network mumbai --name "The Great Shipping Co." --symbol GSC' I get the following error:

`npx hardhat deploy:token --network mumbai --name "The Great Shipping Co." --symbol GSC

An unexpected error occurred:

tasks/deploy-token.ts:4:10 - error TS2305: Module '"@tradetrust/contracts"' has no exported member 'TDocDeployer'.

4 import { TDocDeployer, TradeTrustERC721 } from "@tradetrust/contracts";
           ~~~~~~~~~~~~
tasks/deploy-token.ts:5:33 - error TS2307: Cannot find module '@tradetrust/contracts/contracts/utils/TDocDeployer' or its corresponding type declarations.

5 import { DeploymentEvent } from "@tradetrust/contracts/contracts/utils/TDocDeployer";`

**Comment by superical** [comment]
Heyy! Thanks for pointing this out!🙇‍♂️ 

Looks like an import issue in the deploy script that was missed out in the recent beta version. I will get it fixed and update here shortly.

**Comment by superical** [comment]
@hughht5 I figured I should probably add a post install to run the build. For now, can you try `npm run build` once first before running the deploy command and see if it works for you?

**Comment by hughht5** [comment]
@superical this worked - but i had to add a infura_ID. I took a random one i found online as I don't know how to get one.

After that it worked fine. I then did 
npx hardhat deploy:factory --network mumbai
and
token-registry % npx hardhat deploy:token --network mumbai --name "The Great Shipping Co." --symbol GSC --factory 0x8C48fedC6133e7dA586d15C393aF345517a3059e

looks like it works fine.

Thanks

**Comment by superical** [comment]
Glad that it works for you now, @hughht5. 🎉

I initially thought the issue you had was due to an import problem but turns out that it was simply because the build step wasn't run. I mentioned in a previous comment thinking I should add a post install so that future users will not miss out this step, but have also recalled later that this isn't necessary because currently the build step will already be run automatically when you install the packages. Perhaps you might have cleared the build at some point and hence the files could not be imported?

I might just add a note in the readme to remind about the build step for future users.

As for the Infura ID, you can sign up for one on their website.
