### ISSUE TITLE
Error while performing Endorse change of owner and Endorse transfer of owner actions.

### ISSUE THREAD

**Issue by x-ajnashp** [Open-Attestation/token-registry#14]
Hi, 
I am trying to implement Trade Trust functionalities such as **Issue Transferable document**, **Perform title transfer**, and **Surrender document** into our application using Metamask.  But from 22 Sep I am facing some issue while performing **Endorse change of ownership** and **Endorse transfer of ownership**. It's failing with the "gas required exceed" error(pls ref image no 1). 

The document is valid verified using tradetrust.io. And other actions such as **Transfer holder** and **Nominate new owner** are working fine. 

I tried to do the same action in the tradetrust.io site for the same .tt file. But there also I am getting the same error (image no 2).  Also, I tried using a different token registry.

Attaching .tt file for your reference. 

[Demo Bill Of Lading.txt](https://github.com/Open-Attestation/token-registry/files/5298608/Demo.Bill.Of.Lading.txt)

Error screenshots:-
1.
![TT-endorse-issue-pic-2](https://user-images.githubusercontent.com/41932668/94552350-4cf79080-0289-11eb-940c-9472a4d86401.PNG)

2.
![TT-endorse-issue-pic-1](https://user-images.githubusercontent.com/41932668/94552356-4e28bd80-0289-11eb-8071-38c772ed4c6a.PNG)

**Comment by justussoh** [comment]
Hi @x-ajnashp,

May i know how your token registry is generated? 

Also, i tried droping your sample file, it seems to be not issued and has a invalid identifier. Do you have a valid file so i can takr a closer look?

Thanks

**Comment by x-ajnashp** [comment]
Hi,

I used cli option to create token registry.

Sorry I forget to mention that I used rinkeby test network to generate token registry and issue document.

**Comment by justussoh** [comment]
@x-ajnashp I can't seem to replicate the error based on the steps given, may i know whihc version of the open-attestation cli you are using?

**Comment by justussoh** [comment]
@x-ajnashp I think your version of token-registry may be too old, could you try redeploying a token registry to the latest version using oa-cli@2.3.0

**Comment by x-ajnashp** [comment]
@justussoh I tried to create the token registry in following methods:

1. Using open-attestation cli
version: @govtechsg/open-attestation-cli@1.27.0

2. Using UI option from the token-registry module using metmask as the provider:
version: "@govtechsg/token-registry": "^2.3.0"

In both cases, I was able to issue a document and verify using https://rinkeby.tradetrust.io/. And Transfer holdership and Nominate new owner working, but Transfer ownership not working.

I have created a sample repo for testing.

https://github.com/x-ajnashp/tt-sample-reppo

**Comment by x-ajnashp** [comment]
Hi @justussoh,  I tried to issue a document using oa-cli instead of UI and Metamask, and its working fine. All the actions were able to perform on the document.

**Can you please confirm whether issuing document using the "token-registry" module and Metamask is possible without using oa-cli?**

**Comment by justussoh** [comment]
Hi @x-ajnashp, issuing document using Metamask should be possible. Let me just take a look at your repo! Give me a second.

**Comment by justussoh** [comment]
Hi @x-ajnashp i took a look at your sample repo and I found the error. It lies in this function:
```js
async titleEscrow() {
		const factory = new TitleEscrowFactory(this.signer);
		const signerAddress = await this.signer.getAddress();
		this.escrowTitleInstance = await factory.deploy(this.formData.tokenRegistryAddress, this.formData.ownerAddress, this.formData.holderAddress, factory.address ,signerAddress);
		this.wrappDocument();
}
```
Here we can see that you are deploying a new `titleEscrow` to own the token minted. However, `factory.deploy` function has the wrong/missing parameters. The last parameter should not be `_titleEscrowFactoryAddress` instead of signer address. 

The error occurs because when we try to transfer ownership, a new` titleEscrowB` must be created. This is done by the `titleEscrowA` connecting to the `titleEscrowFactoryAddress` to deploy a new `titleEscrowB` with new `owner/bene & holder` and transferring "ownership" in the token registry to `titleEscrowB`.

Our error occurs because of `titleEscrowA` connecting to the `signerAddress` to try to deploy a new `titleEscrowB` which method doesn't exist.

To see how deploying can be done correctly, you can refer to this:
[https://github.com/TradeTrust/document-creator-website/blob/master/src/services/publishing/publishing.ts#L46](https://github.com/TradeTrust/document-creator-website/blob/master/src/services/publishing/publishing.ts#L46)

PS: 
- `TitleEscrowFactory` !== `TitleEscrowCreator`
- `TitleEscrowCreator` for the file linked it precreated and reused
